# Generated by Django 5.1.2 on 2024-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_integration', '0002_emailmessage_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='account',
        ),
    ]
