# Generated by Django 5.1.2 on 2024-10-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_integration', '0004_emailmessage_email_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='attachments',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='email_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail_integration.emailaccount'),
        ),
    ]
